#!/usr/bin/env bash
# Pre-write hook: block writes that introduce common mistakes.
# Receives tool input as JSON on stdin.
# Exit 0 = allow, exit 2 = block with message.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // empty')
CONTENT=$(echo "$INPUT" | jq -r '.content // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# --- 1. Never overwrite generated files ---
if [ -f "$FILE_PATH" ]; then
  HEAD=$(head -5 "$FILE_PATH")
  if echo "$HEAD" | grep -q "^// Code generated" || \
     echo "$HEAD" | grep -q "^# Generated by" || \
     echo "$HEAD" | grep -q "^# Auto-generated" || \
     echo "$HEAD" | grep -q "^# DO NOT EDIT"; then
    echo "BLOCKED: $FILE_PATH is a generated file. Fix the generator, not the output."
    exit 2
  fi
fi

# --- 2. Catch hardcoded secrets ---
# Look for common secret patterns in the content being written.
# Only check non-test, non-example files.
case "$FILE_PATH" in
  *_test.go|*_test.py|*.test.ts|*.test.tsx|*.spec.ts|*.spec.tsx|*test_*|*example*|*testdata*|*conftest*|*fixture*|*.md) ;;
  *)
    if echo "$CONTENT" | grep -qEi '(AKIA[0-9A-Z]{16}|-----BEGIN (RSA |EC )?PRIVATE KEY|ghp_[a-zA-Z0-9]{36}|sk-[a-zA-Z0-9]{48}|password\s*[:=]\s*"[^"]{8,}")'; then
      echo "BLOCKED: content looks like it contains a hardcoded secret. Use environment variables."
      exit 2
    fi
    ;;
esac

# --- 3. Protect linter/formatter config ---
# Don't let the agent weaken rules to "fix" lint errors. Fix the code, not the config.
case "$(basename "$FILE_PATH")" in
  .eslintrc*|eslint.config*|.prettierrc*|prettier.config*|biome.json*|\
  .golangci.yml|.golangci.yaml|\
  ruff.toml|.ruff.toml|pyproject.toml|\
  tsconfig.json)
    if [ -f "$FILE_PATH" ]; then
      echo "BLOCKED: $FILE_PATH is a linter/formatter config. Fix the code, not the rules."
      exit 2
    fi
    ;;
esac

# --- 4. Block dangerous SQL without safeguards ---
if echo "$FILE_PATH" | grep -qiE '\.(sql)$'; then
  # DROP TABLE / DROP COLUMN without IF EXISTS
  if echo "$CONTENT" | grep -qiE 'DROP\s+(TABLE|COLUMN)' && ! echo "$CONTENT" | grep -qiE 'IF\s+EXISTS'; then
    echo "BLOCKED: DROP without IF EXISTS in $FILE_PATH. Add IF EXISTS or confirm this is intentional."
    exit 2
  fi
  # DELETE/UPDATE without WHERE
  if echo "$CONTENT" | grep -qiE '^\s*(DELETE\s+FROM|UPDATE\s+\w+\s+SET)' && ! echo "$CONTENT" | grep -qiE 'WHERE'; then
    echo "BLOCKED: DELETE/UPDATE without WHERE clause in $FILE_PATH. This affects every row."
    exit 2
  fi
fi

# --- 5. Prevent giant files ---
# Holzmann rule 4: no function longer than a page. Proxy: no file over 500 lines.
if echo "$FILE_PATH" | grep -qE '\.(go|py|tsx?|jsx?|sql)$'; then
  LINE_COUNT=$(echo "$CONTENT" | wc -l)
  if [ "$LINE_COUNT" -gt 500 ]; then
    echo "WARNING: $FILE_PATH is $LINE_COUNT lines. Consider splitting into smaller files."
  fi
fi

exit 0
