[project]
name = "simple-agent"
version = "0.1.0"
description = "Simple agent just for testing"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.135.2",
    "httpx>=0.28.1",
    "pydantic-settings>=2.13.1",
    "strands-agents[openai]>=1.33.0",
    "strands-agents-tools>=0.3.0",
    "uvicorn>=0.42.0",
    "redis>=7.4.0",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]
